name = "wedding-rsvp"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
AIRTABLE_BASE  = "appivWbWyQlQqGJTB"
AIRTABLE_TABLE = "tblfcALpXOklfXfG0"
GUESTS_TABLE   = "tbllrariezt3kKrsq"

# Secret (set once, never commit):  wrangler secret put AIRTABLE_TOKEN
